apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  labels:
    project: applications
spec:
  description: Business applications and developer tools

  # Source repositories
  sourceRepos:
    - "https://github.com/fede-r1c0/homelab"
    - "https://backstage.github.io/charts"
    - "https://bitnami-labs.github.io/sealed-secrets"

  # Destination clusters and namespaces
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc

  # Cluster resource allow list
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
    - group: "bitnami.com"
      kind: "*"

  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: StatefulSet
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "networking.k8s.io"
      kind: NetworkPolicy
    - group: "bitnami.com"
      kind: "*"
  # Sync policy disabled for compatibility
  # syncWindows:
  #   - schedule: "0 0 * * *"
  #     duration: 24h
  #     kind: allow
