apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  labels:
    project: monitoring
spec:
  description: Monitoring and observability applications

  # Source repositories
  sourceRepos:
    - "https://github.com/fede-r1c0/homelab"

  # Destination clusters and namespaces
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc

  # Cluster resource allow list
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
    - group: "monitoring.coreos.com"
      kind: "*"
    - group: "grafana.com"
      kind: "*"
    - group: "loki.grafana.com"
      kind: "*"
    - group: "tempo.grafana.com"
      kind: "*"

  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: PersistentVolume
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: StatefulSet
    - group: "apps"
      kind: DaemonSet
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "networking.k8s.io"
      kind: NetworkPolicy

  # Sync policy
  syncWindows:
    - name: allow-sync
      schedule: "0 0 * * *"
      duration: 24h
      kind: allow
      applications:
        - "prometheus-stack"
        - "loki"
        - "tempo"
