apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
  labels:
    project: security
spec:
  description: Security and compliance applications (sealed-secrets, OPA Gatekeeper)
  sourceRepos:
    - "https://github.com/fede-r1c0/homelab"
    - "https://bitnami-labs.github.io/sealed-secrets"
    - "https://open-policy-agent.github.io/gatekeeper/charts"
    - "https://charts.community.cloudflare.com"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
    - group: "admissionregistration.k8s.io"
      kind: ValidatingWebhookConfiguration
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration
    - group: "bitnami.com"
      kind: "*"
    - group: "policy"
      kind: PodDisruptionBudget
    - group: ""
      kind: ResourceQuota

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: StatefulSet
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: "bitnami.com"
      kind: "*"
    - group: "batch"
      kind: Job
    - group: "policy"
      kind: PodDisruptionBudget
    - group: ""
      kind: ResourceQuota
