{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "minio-loki-credentials",
    "namespace": "monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "minio-loki-credentials",
        "namespace": "monitoring",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "accessKeyId": "AgBxo7L/SIc0qG4cOp2zpKe5pB6p83WV3o92++CpBKkOn31xc+ucYmU2+AIchFIwgOONx+L/duglKDlQwr6RpyL73bPxOpy1tIiMvOO7XrIVlhyxIE3x9YsNO1HxjanRQJZPS45Sn8mjG3d9jKCNpDaVVEyxT12UXuMdyG8HMGUafzjfE1YVRknA+u2ApUAkmaNyBQimzWEwo/ajAsu4UjN3tZ6+H9n5YbxnKNAKhE6B8hPx07pWb9bGQnEUaMSD9ZyN+QsLNBtJZcpodh+rAx53VlGYt+pHdD+KjeU4gYU+2WdatS4ZpvtTNo7vqJY67jjey5p54rPm7Npk4b+sUohng1ouQOb0O5f0VUTSEdeT3YMOQqRpl8YIPrLVUcTuJelE2SUv6drBbt9Zk/Yxk2oMyMDHQybSFMATNVsNQko1nZGTu0V/rdtU2fYNmbtM9uCZOrNhyRkAjMk7W6t+LpVt254PNEj/sqgx84z9RFqtMEOPi7votzuNWN+3hNyKU+EezxGKgl2jFW/mis1zc21xzfEc0RjD+0ALRH5+nJtOkC1pgy6LLNfpazc7hhFKcgou13lOLS/ppd65b1AzjGqUXX4dLpJQkume5AXUhQ/De5BqM7kQJQ+9vkYS3eumJVgzQFeu+ll66rnVh8ehaakyX3gsV842S7t6rjjajorJ2pCRXC20g2ckTnZJi3eOnHp7N3Y00N0kQxeK3ZeJosKX0gI3Gw==",
      "secretAccessKey": "AgDAHf7+Epqf8LNMx0FV2HweT9YiMAsDRaeWCr/dpjsnOYhtk8GKBO3hKAbCTIEQ5DszFs3hl+wo5/MyyjIcTdXeZ4EHC/3pvSsHMdZucKCb6QHy+CIKJ6DmAnuUQ4ZKXtClcYLAkYpD3r6AQ/fa08+s1z1udP8YKlyUCWpxBO5x8n+vlWw5wQgH7MajLNo3WV4FVnBtft7omk5xu+V4TzLzovvXLVKZATuc5JjMSb4JqaskRgLqla8Ie9hznTs3Y2+Zzo1COqb8C/HklMG13dau9L70LfEmDLqYJP7PbMoiMDnsvQY8pO1ddL2D2ZiVgsRCoyfZ0pmObe+7wTlJZhRHEKaTNb+uEsZ7oTv5HygEv9pyeh4FOqWJiRqJLzM467mrmceyFGhI6mxRiDZxlpdbw9E+o/J3lQBwzBbUTzASaJKJm4kl5pRffelNgDIB28gWfp/gpJRJYhjcPYvdkR4tUxAG/di/oySqcvjHyJ1Ela5DhkAkDq8VrP/DAjjAaViqvRBM3C2ymhVL99hDXpt55G2OmMU4dzfnfodOZGKQJh0PJWclomcVfoM6XGK1K+impt0hi+YbRjmr2ZxMufgix6Tv3bOsMAKXTzehT0ZmuKxbrm97AEWxzLagd2QTcPxOnK80NPFWsc9tLwodxAJtWKd3JDeCHYMPhKaj19x7hzIUb5+SF/98ZV/39cjf7NJLGgSMh492vKkJ+OkBxXqYcI0GpA2NPHLudTm2qs8X+1+0ZioZm8oi"
    }
  }
}
