# Loki Configuration for Raspberry Pi Single-Node Cluster
# Optimized for home lab environment

deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  resources:
    limits:
      cpu: 400
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi
  extraEnv:
    # Keep a little bit lower than memory limits
    - name: GOMEMLIMIT
      value: 900MiB

# Zero out replica counts of other deployment modes
#deploymentMode: SimpleScalable
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

# Loki configuration
loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage_config:
    aws:
      region: us-east-1
      bucketnames: loki-chunk,loki-ruler,loki-admin
      s3forcepathstyle: false
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 72h # 3 days retention

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunk
      ruler: loki-ruler
      admin: loki-admin
    s3:
      # AWS endpoint URL
      endpoint: minio.minio.svc.cluster.local:9000
      # AWS region where the S3 bucket is located
      region: us-east-1
      # AWS secret access key
      secretAccessKey: ${MINIO_ACCESS_KEY}
      # AWS access key ID
      accessKeyId: ${MINIO_SECRET_KEY}
      # AWS signature version (e.g., v2 or v4)
      signatureVersion: v4
      # Forces the path style for S3 (true/false)
      s3ForcePathStyle: true
      # Allows insecure (HTTP) connections (true/false)
      insecure: true
      # HTTP configuration settings
      http_config: {}

chunksCache:
  enabled: false
  # default is 500MB, with limited memory keep this smaller
  writebackSizeLimit: 10MB
