# kube-prometheus-stack Configuration for Raspberry Pi Single-Node Cluster
kube-prometheus-stack:
  crds:
    enabled: true

  # Prometheus optimization
  prometheus:
    enabled: true
    prometheusSpec:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 5Gi # Conservative storage for homelab

  # Grafana optimization
  grafana:
    enabled: true
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 100m
    service: # Changed from ClusterIP to LoadBalancer
      type: LoadBalancer
    admin: # Changed from adminUser/adminPassword to existingSecret
      existingSecret: "grafana-secret"
      userKey: "admin-user"
      passwordKey: "admin-password"

  # AlertManager optimization
  alertmanager:
    enabled: true
    alertmanagerSpec:
      resources:
        requests:
          memory: 32Mi
          cpu: 25m
        limits:
          memory: 64Mi
          cpu: 50m
