# Sealed Secrets Configuration for Raspberry Pi
# Optimized for single-node cluster with limited resources
sealed-secrets:
  resources:
    requests:
      memory: 64Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
