# Sealed Secrets Configuration for Raspberry Pi
# Optimized for single-node cluster with limited resources

# Controller configuration
controller:
  # Resource limits optimized for Raspberry Pi
  resources:
    requests:
      memory: 64Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m

  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001

  # Service configuration
  service:
    type: ClusterIP

  # Metrics configuration
  metrics:
    enabled: true
    service:
      type: ClusterIP

  # High availability (disabled for single node)
  replicaCount: 1

  # Pod disruption budget
  podDisruptionBudget:
    enabled: false

  # Pod security policy
  podSecurityPolicy:
    enabled: false

  # Network policy
  networkPolicy:
    enabled: false

# RBAC configuration
rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    - apiGroups: ["bitnami.com"]
      resources: ["sealedsecrets"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Service account configuration
serviceAccount:
  create: true
  name: "sealed-secrets-controller"
  annotations: {}

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Ingress configuration (disabled for single node)
ingress:
  enabled: false

# TLS configuration
tls:
  enabled: false
