---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    cert.pem: AgA4GSePe6VHDV5/qOL216fLtJBT459RO1ESsHVfjYxzfuGhExZZeuKs6hWTLGrlweH6ySPJPIECVAdPKwSwj5ISlHMJCO8j8xuJDFqfit/C8ZjnsBZ6wkn7lD5/tMq1alpx7p0XANdB7YBgV+6uVAEAhOYiCVpufh8+ZUQH//l5RtVaajDNjLrJZlIprZ97UNjvOJHdW0SsB+qIu8A521pX+GEmAxV4LSxRJ3Ljxm+W+11FK+zm77NX3Fpo1L+7DvirsIWrG8HcRRN7lp7OgdlkcCOUeW6k4ZmBKQd8VKpdYh/5wC7tZkbbzvD7zZDQXLI4cYYjRVoSb2GvlTw1vMP+7ryqQCvgCtXm4fcJx3NdGhaaQAp3YKeVEuZoWlxoGge8v9+YHZYPbjMz0FZXH1y4giFHeE16LhEuhR16VkIMmAi9LoRWFH8YtobAhEw8/4UaBhhNevPULAUSyhNtgt20GYsJpgtXKJ7f21TdKMRThNWDFzrlLnCBY3ZzWUBR1hVdSyPOzuHqWej/sFqXgEqcIYLhlrAcNu3oKwmCEcfLVupudYDN2nmf5ZcnlhlMsAZz3CIJsSjX6iDZfcY5Caz7ZDMUbvirSRcuSbTXTASw2ckEdJ1OIc0THTB7Hg2O39hRy5tfTq3B4OEg2WGi0Pz3Twj5CT0wVEoVQi46OE7dqStw7TGxrmofm1IZG601w56kC92ryOmcVU03wwc51ZR5U2apyQGRA/9G2Vf/qdT+YqFXgchhHZxB17z92lOdZUoXIX25OiGs315aELDtbqwtJVhdWtwo54UDbFmcHpC07XoSVImc9Dg+qpxFOvTa56X0gtTVkc4OtMmihD4SVrFTRttLThG8ebnsxEsCuTMOyJus9moYsn+ieBHffuK8DGx3ITQg0LPbZNjtzUUDENCo7AXkvTMR+fEHP5Z8YzmR24zor+7QrheicS8jkNADIhZpo8W0sp/HymEfPGcWBU2N8qaHvutP7Ly6rvmZvvBxWRZZO0cJSQocTUqTmAUbIA/1nQPcexHCBN1DmyMpOLdYLpLnpRnCcBjxew==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-secret
      namespace: cloudflare-tunnel
    type: Opaque
