apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  labels:
    project: applications
    phase: "6"
spec:
  project: applications
  sources:
    - repoURL: https://backstage.github.io/charts
      chart: backstage
      targetRevision: 2.6.1
      helm:
        valueFiles:
          - $values/apps/backstage/values.yaml
    - repoURL: https://github.com/fede-r1c0/homelab
      targetRevision: HEAD
      ref: values
      path: apps/backstage
      directory:
        include: "backstage-sealedsecret.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
