apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    project: bootstrap
    phase: "2"
spec:
  project: bootstrap
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.15.2
      helm:
        valueFiles:
          - $values/apps/metallb/values.yaml
    - repoURL: https://github.com/fede-r1c0/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/fede-r1c0/homelab
      targetRevision: HEAD
      path: apps/metallb
      directory:
        include: "metallb-config.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
