---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBhlmFI1bc3ZGcWzAafuMgJEUCKjiV/aMpTBlwcZdThfS7sdo1DuvLSJB6lJeNzcjMoaMy/l+Pzx8mhfRBM6vG9REXMnwsaKR+tP7q/zWzJ/Ls3i1MO5UyYm1v2ZlfzRNRE4Kz8r47qd94gyGShLencd/wkhgQzKMwuVku7xovralkG5BQuZgRhrShfn9GtLIpXV5HqY1I/XOTqfwuhTSTIirkeFFGDNVYjczBEoUZy/Gm7APyv8ON5rvB30s8tr0fhUbachrfF6M9UCiAznG2j7SdGy/3rTw9Kwb4ZRrdZUIsdUE8zzycZXC1BTVnHSTkdK6Z4XHPLCcw5Xh83YG2Ddx8glKqyIOr9W1Sxk31Bl7lC1goXsIZFtFdTAeQ94uCbbzxQIISrCYxrDr5sqWAjsKYqTHeVSfu7KoFWz16Cs+D2+sjAwELK01famHFPXruM03jQXcgn68w+cGwOFY85Vd7BC4EM54z+8fK1fze6ReN2YjxQuQllXaOnYwlkh91WDutszUQO7mB2EiIqvyxr0RlN8rEp99co0MK1D5/8Kb5fSpXp49xnrdeaW1SxGZ/LUp5/+72sDbvq9jsGXJfzOtvEivyxk7fxPqu5pSIbMDXMbd4iOecVw1Ixtbuuwj+VdR80EUmyifyb+Zbgg4+SxHnCwbLBo3VQCsJZcf5WBypGjtLgCFZDJUniBg5N5SHF6N/5XdJkghQ8SOVJ9PyDlA0+9daq9z88xw==
    admin-user: AgAqfdbnJbi9AOIgSktaMecNURZrVpTAD/EQG/8wtvsMWRuV3vovRZHVG3LfkvcGKOq9660HlUWELh2LyU+BuIabwH1xecQ1PSUGhh1YytwiTmbLApnRDPdce/kJ5ZS8vIylzryC4ipQIoWBN/3ZwLb/z9ymcEFsr7V74qi7lmMrq4dDpIHgcZwWersagsxTR2R2fpJXl89N63v8XZJ1W6d2M+iEEIEE5MWY03Nn1gP5xP5x2PDL8CPnLkyaf70flXF/WZBSLLncluqP9AYgLccu/UOa7s6Owc2hO6ACWTLuMhQH/sC3qJkXAZZSRb9RaL5o5mfWAO+Bg686d0mDT8wdh/I8ALg8mPbFolmXDhDHCb4yPwpBfZ7oUI0mZ2i2m1AtRT2k972bdG/mmqGmMNKXMoJp8/CtzOL2+Byk+O0t4V5UPLfHSBy0oX4jAvH8XN9NIto5T0MPbhA+ZZzpNrtEdKfMj0Af4xXXfh9qor0K4LAo553wutzKuN8S2yeS67VDGPmdcREreRbF6bNpulZu6ZIot8u0bUwufpmx9v83yJits3nXrV19YN36Rq7FG+Dg3aOiu+wxzdwb0oairp+8zoySdr4OKENBxq8els/sHlrKaD4ZuXP7yLMao2OQ/XTy7TMft0nILRXjH9+BKjd93lYS9D6GjvjgQ/2B2IirRBoQwHCBbayCA4rglfkGBp+k3VfeQaCvBDfKeCab
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: kube-prometheus-stack
      name: grafana-secret
      namespace: monitoring
    type: Opaque
