# OPA Gatekeeper Configuration for Raspberry Pi Single-Node Cluster
replicas: 1

logLevel: INFO

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

customResourceDefinitions:
  create: true
