# OPA Gatekeeper Configuration for Raspberry Pi Single-Node Cluster
replicas: 1

logLevel: INFO

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

customResourceDefinitions:
  create: true
