# OPA Gatekeeper Configuration for Raspberry Pi Single-Node Cluster
replicas: 1

logLevel: INFO

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

customResourceDefinitions:
  create: true
